### ISSUE TITLE
add missing NL and RO translation

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#373]
@harrieklomp, @andrixnet Could you add NL and RO translation please? Please see in commit:
https://github.com/opencaching/opencaching-pl/commit/4b0d6dcde073abf16012d4833d86af201506713b

This is displayed when user did not specified his home coordinates.

**Comment by harrieklomp** [comment]
Done in Dutch and German language files.

**Comment by following5** [comment]
#391 will show you any translations which are still missing. I suggest to merge that pull request first before further translation updates.

**Comment by mzylowski** [comment]
@andrixnet 
There is still something to do?
We can close it? This issue is related only with one commit.

**Comment by mzylowski** [comment]
We have #423 for translation discussion.

**Comment by andrixnet** [comment]
@mzylowski I checked and this was fixed quite some time ago, in a batch with other changes. Yes, safe to close.
